# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#

version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-2.7
jobs:
  # Based on answer https://discuss.circleci.com/t/run-tests-on-multiple-versions-of-python/15462
  test-2.7:
    docker:
      - image: circleci/python:2.7
    working_directory: ~/repo27

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-27-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-27-dependencies-

      - run:
          name: activate virtualenv and install dependencies.
          command: |
            mkdir -p ./venv
            virtualenv ./venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            coverage run --source="." --rcfile=.coveragerc manage.py test
            coverage report --fail-under=51 --rcfile=.coveragerc -m
            pycodestyle ./eox_azure
            pylint ./eox_azure --rcfile=./setup.cfg
